<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Core.Model\Core.Model.csproj" />
    <ProjectReference Include="..\Core.Store\Core.Store.csproj" />
    <ProjectReference Include="..\Core.Rules\Core.Rules.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
